- .github/workflows/release.yaml
The action uploads the files (build .zip + sha.txt) to the release and updates the version in the package.json
#15
> feat: add release.yaml

- src/result_transformer.ts
> fix: show a correct legend when set to Auto

- CHANGELOG.md
- pkg/plugin/query.go
- src/consts.ts
- src/datasource.tsx
- src/module.ts
- src/partials/annotations.editor.html
- src/querybuilder/components/LabelParamEditor.tsx
> Add annotation support

- src/components/monaco-query-field/getOverrideServices.ts
Add implement required methods for query field. Without them, the query field does not work correctly.
> fix autocomplete for query filed

- CHANGELOG.md
- README.md
- package.json
- victoriametrics-datasource-v0.1.1.zip.sha1
Update version, README and CHANGELOG
> release-0.1.2

- pkg/plugin/query_test.go
- pkg/plugin/step.go
- pkg/plugin/step_test.go
Fixed and improved step calculation when we have a long time range.
> pkg/plugin: fix show annotations and step calculation

- CHANGELOG.md
- src/components/PromLink.tsx
- src/components/PromQueryEditor.tsx
- src/components/VmuiLink.tsx
- src/querybuilder/components/PromQueryEditorSelector.tsx
- src/utils/time.ts
> Add links to VMUI from the query panel

- .github/workflows/pr-checks-golang.yml
- .github/workflows/pr-checks.yml
- .github/workflows/pr-codeql-analize-golang.yml
- .golangci.yml
- Makefile
- deployment/docker/Makefile
- pkg/plugin/query.go
- pkg/plugin/query_test.go
- pkg/plugin/response.go
- pkg/plugin/response_test.go
Added checks for golang by:
1. gofmt
2. go vet
3. golangci-lint
Added action for tests run
Added action which checks build
> pkg/plugin: add github action for golang

- CHANGELOG.md
- src/components/VmuiLink.tsx
- src/configuration/ConfigEditor.tsx
- src/configuration/PromSettings.tsx
- src/configuration/TipsSetup.tsx
- src/datasource.tsx
- src/types.ts
Added the ability to change the `vmui link` in the datasource settings.
- #61
> feat: add ability to change the link on vmui

- README.md
The readme looks a little bit wrong with the format
> readme markdown format

- CHANGELOG.md
- package.json
> update CHANGELOG.md, update package.json

- CHANGELOG.md
- src/services/TimeSrv.ts
This PR resolves issue #47 by ensuring variables correctly update to match the user-selected time range.
> Fix time range update for variables

- CHANGELOG.md
- package.json
Updated package.json version and CHANGELOG.md
> pre-release updates

- pkg/plugin/datasource.go
- pkg/plugin/query.go
- pkg/plugin/query_test.go
- pkg/plugin/response.go
- pkg/plugin/response_test.go
> fix: correct the display of the legend

- README.md
See: https://github.com/VictoriaMetrics/grafana-datasource/issues/109
> doc: update readme to include more secure config for k8s

- README.md
- add grafana datasource example
- fix list numbering, make numbering to use `1.` for consistency
- minor formatting update for numbered lists
> doc: update readme to include example with Grafana datasource

- README.md
Rebased version of https://github.com/VictoriaMetrics/grafana-datasource/pull/111
> Icyfork doc grafana operator usage

- .config/jest.config.js
- jest.config.js
- src/querybuilder/parsing.ts
Fixed parsing query in builder
Ref issue: #112
> fix query builder

- CHANGELOG.md
- src/datasource.tsx
> fix angular warning

- CHANGELOG.md
add changes from PR #120 to CHANGELOG.md
> docs: add changes from #120 to CHANGELOG.md

- CHANGELOG.md
- package.json
> Pre release

- CHANGELOG.md
- package.json
Made pre-release changes in the CHANGELOG and package.json
> pre-release changes

- README.md
Adding additional option to install plugin as part of the Grafana helm chart.
> adding plugins section as an option for installation in helm.

- src/querybuilder/operations.ts
> label_join unexcepted interaction

- packages/lezer-metricsql/src/metricsql.grammar
- src/querybuilder/aggregations.ts
- src/querybuilder/metricsql-functions/basic/index.ts
> adhoc result in unexpected request

- CHANGELOG.md
- package.json
> make pre-release changes

- CHANGELOG.md
Updated CHNAGELOG.md with bugfix description
> followup after 6f94c8a0393dd856759157db7c1c54c65d7e9a36

- CHANGELOG.md
- package.json
> make pre-release

- CHANGELOG.md
- package.json
> Prepare pre-release changes

- CHANGELOG.md
- pkg/plugin/datasource.go
same as https://github.com/VictoriaMetrics/victorialogs-datasource/pull/92
> fixed healthcheck

- CHANGELOG.md
Updated changelog with last changes
> make follow up with CHANGELOG.md updates

- Makefile
Fixed archive script. Removed the plugins folder
> fix archive script

- CHANGELOG.md
- package.json
> make pre-release updates

- Makefile
- README.md
Updated build script change version on README.md
> update build script change version on README.md

- CHANGELOG.md
- Makefile
- package.json
Fixed checksum calculation to pass the plugin check procedure
> Fix release checksum

- package.json
- yarn.lock
> fixed security issues

- CHANGELOG.md
- src/components/PrettifyQuery.tsx
Fix issue with "Prettify query" functionality corrupting dashboard JSON configuration by splitting query expressions into individual characters. 
Ref issue: #242.
> fix "Prettify query" functionality corrupting dashboard JSON

- README.md
- package.json
Added a new version to the package.json and in the Readme before the release
> pre release updates

- CHANGELOG.md
- README.md
- package.json
Updated  CHANGELOG.md, README.md and package.json to make release
> update CHANGELOG.md, README.md and package.json

- .github/workflows/pr-checks-frontend.yml
- .github/workflows/release.yaml
- Dockerfile
- package.json
upgraded node version to a latest 20.18.9 and show message if no signing key set
> node upgrade and added secrets to env variables

- CHANGELOG.md
- README.md
- package.json
Clarify how to make a new release in the README.md.
Update the package.json and CHANGELOG.md before the release
> update in the README.md how to make new release

- README.md
- src/README.md
@AndrewChubatiuk @zekker6 I'm not sure about correctness of grafana-operator installation - could you please check that?
> docs: update guides to install signed plugin

- package.json
Updated version of the plugin before the release
> update version of the plugin

- .github/workflows/docs.yaml
do not ignore not exiting yet files in docs repo, export target path
> docs: export target path

- .github/workflows/docs.yaml
> docs: fix image path

- .github/workflows/release.yaml
> added attestation

- package.json
Update plugin version before release
> Update version of the plugin before the release

- CHANGELOG.md
- package.json
- yarn.lock
added missed notes and plugin version bump
> release 0.15.0-alpha1

- CHANGELOG.md
- package.json
> release: 0.15.0

- CHANGELOG.md
- package.json
> release: 0.15.1

- CHANGELOG.md
- package.json
- packages/lezer-metricsql/package.json
- packages/lezer-metricsql/src/highlight.js
- packages/lezer-metricsql/src/metricsql.grammar
- packages/lezer-metricsql/src/tokens.js
- src/querybuilder/PromQueryModeller.test.ts
- src/querybuilder/binaryScalarOperations.ts
- src/querybuilder/parsing.test.ts
- src/querybuilder/types.ts
- yarn.lock
Adds support for the `default` binary operator in the Visual Query Builder, so expressions like `metric default 0` work directly in builder mode. Related issue: #296.
> feat: add support `default` binary operator

- .golangci.yml
- Makefile
- pkg/plugin/datasource.go
- pkg/plugin/datasource_test.go
- pkg/plugin/query_test.go
- pkg/plugin/response_test.go
- pkg/plugin/step_test.go
- upgrade golangci-lint
- rewrote tests using f-tests pattern
> refactoring: rewrote to f-tests, upgrade golangci-lint

- package.json
Updated version of the plugin before the release
> update plugin version before release

- package.json
Updated plugin version with the fix
> update plugin version

- CHANGELOG.md
- pkg/main.go
- pkg/plugin/datasource.go
- pkg/plugin/response.go
- src/components/PrettifyQuery.test.tsx
- src/components/PrettifyQuery.tsx
- src/datasource.tsx
- src/language_provider.ts
- src/plugin.json
- src/types.ts
Fixed regression after the plugin check
> fix regression implemented in the commit 115d740

- CHANGELOG.md
- pkg/plugin/query.go
- pkg/plugin/query_test.go
Related issue: #350 
Fixed handling of 'auto' legend mode to ensure correct series label generation.
> fix handling of 'auto' legend mode to ensure correct series label generation

- README.md
required for https://github.com/VictoriaMetrics/vmdocs/issues/164
> docs: ignore direct readme rendering

- README.md
https://github.com/VictoriaMetrics/vmdocs/issues/164
> docs: exclude from sitemap

- package.json
> bump version to 0.19.2
