VictoriaMetrics/victoriametrics-datasource

- deployment/docker/Makefile
the change sets .cache folder as yarn cache folder, which can be reused for consequent builds and speed up packaging.
> reuse yarn cache during plugin builds

- src/datasource.tsx
- src/querybuilder/components/Trace/index.tsx
- src/querybuilder/components/Trace/style.ts
- Add a button to display and copy the JSON version of the trace. #53
- Show tracing on "Explore" page
> JSON version of the trace

- CHANGELOG.md
- src/metric_find_query.ts
Expand regex for `label_values` template function.  Added support to get values from the next queries `label_values(my.label)` or `label_values(my\.label)`
Related issue: https://github.com/VictoriaMetrics/grafana-datasource/issues/74
> fix: fix label_values template functions behavior

- README.md
I should use `-P` option not `-E` for grep command regex because `\d` is Perl Regular Expression which is supported GNU grep.
I found the pull request was merged which fix the -E to -P option before. #65 
So I try to change `\d` to `[0-9]`.
> fix: readme regex

- CHANGELOG.md
- pkg/plugin/datasource.go
- pkg/plugin/query.go
- pkg/plugin/query_test.go
- src/configuration/PromSettings.tsx
This PR addresses a bug that prevented custom query parameters from being properly processed in annotation queries. 
- #95
> fix: handle custom query params in annotation queries

- CHANGELOG.md
- src/components/PromQueryField.tsx
Fix the issue where `metrics browser` displayed `no metrics found` when metrics were present.
Related [issue #98](https://github.com/VictoriaMetrics/grafana-datasource/issues/98)
> Fix the display of metrics in the `metrics browser`

- .eslintrc
- CHANGELOG.md
- src/components/PrettifyQuery.tsx
- src/components/VmuiLink.tsx
- src/components/WithTemplateConfig/index.tsx
- src/datasource.tsx
- src/querybuilder/components/PromQueryEditorSelector.tsx
- add a `prettify query` icon, which when clicked, formats the query. Related [issue #86](https://github.com/VictoriaMetrics/grafana-datasource/issues/86).
- change the style of the buttons `WITH templates` and `Run in vmui` to icons.
> Add support queries prettifying in query editor

- CHANGELOG.md
- Makefile
- README.md
- deployment/docker/Makefile
- pkg/Makefile
Enabled Windows build for backend plugin.
Related issue: https://github.com/VictoriaMetrics/grafana-datasource/issues/67
Signed-off-by: dmitryk-dk [d.kozlov@victoriametrics.com](mailto:d.kozlov@victoriametrics.com)
> deployment: add windows build for backend

- .github/workflows/docs.yaml
- README.md
Copies README.md file as a separate documentation page of main docs.
See: https://github.com/VictoriaMetrics/VictoriaMetrics/pull/5299
> ci: setup copying readme as documentation page

- .github/workflows/docs.yaml
Newline in the beginning of the file breaks Jekyll rendering. Jekyll ignores meta info after newline.
> ci: fix docs copying pipeline

- CHANGELOG.md
- src/components/VmuiLink.tsx
- src/configuration/PromSettings.tsx
- src/datasource.tsx
- A feature has been added to generate a default link for vmui.
- The default vmui link has been changed from `/graph` to `/vmui/`.
- Fixed #132
> fix the default link to vmui

- CHANGELOG.md
- src/legend.test.ts
- src/legend.ts
- Updated the regular expression in the `renderLegendFormat` function for more precise matching.
- Modified the default value in `renderLegendFormat` to return an empty string for undefined labels.
- Revised the test case for `renderLegendFormat` to align with the updated function logic.
- Addressing issue #133
> fix logic for replacing legend label names 

- CHANGELOG.md
- package.json
- packages/lezer-metricsql/package.json
- packages/lezer-metricsql/src/metricsql.grammar
- src/components/monaco-query-field/monaco-completion-provider/completions.ts
- src/components/monaco-query-field/monaco-completion-provider/index.ts
- src/language_utils.ts
- src/querybuilder/components/MetricSelect.tsx
- yarn.lock
This pull request introduces support for metric names containing special characters.
Supported special characters: `-`, `+`, `*`, `/`, `%`, `^`, `=`
Key Changes:
1) Fixed the logic for switching between builder and code modes for metric names with special characters.
2) Added an escaping character when inserting metrics with special characters from the autocomplete in code mode.
#131
> add support for special characters in metric names

- CHANGELOG.md
- src/datasource.tsx
- src/language_utils.ts
The pull request fixes escaping in metric names with special characters in requests for obtaining `label=values`.
Ref: #140 and https://github.com/VictoriaMetrics/grafana-datasource/issues/131#issuecomment-1919127947
> fix the queries for `Label Filters` and `Metrics Browser` for metrics with special characters

- CHANGELOG.md
- src/variables.ts
This pull request addresses the issue where the this context was lost in the template variable service, leading to errors when processing template variables. 
By converting the function to an arrow function, we ensure the this scope is preserved.
#150
> Fix template variable service errors

- README.md
I get the following error while following the instructions:
```sh
$ tar -xf plugin.tar.gz -C ./victoriametrics-datasource
tar: victoriametrics-datasource: Cannot open: No such file or directory
```
Also I noticed the package already contains everything within `victoriametrics-datasource` directory inside the archive, so unpacking into current directory seems like a right thing.
> Update unpacking instructions

- CHANGELOG.md
- packages/lezer-metricsql/package.json
- packages/lezer-metricsql/src/metricsql.grammar
- yarn.lock
fix parsing of label names with special characters for the query builder
[ #131](https://github.com/VictoriaMetrics/grafana-datasource/issues/131#issuecomment-210566217)
> Fix parsing of label names with special characters

- README.md
- Use "GF_INSTALL_PLUGINS" environment variable to perform plugin installation instead of shell script.
- Simplify docker-compose based example by using pre-built image, fix path for provisioning config.
> docs/readme: simplify installation instruction

- CHANGELOG.md
- src/components/PrettifyQuery.test.tsx
- src/components/PrettifyQuery.tsx
Fixed issue with prettify query if if the query includes Grafana variables in the lookbehind window.
See this issue: https://github.com/VictoriaMetrics/grafana-datasource/issues/166
> fix an issue with prettify query

- src/datasource.test.ts
- src/datasource.tsx
> fix ad hoc filter replace bug

- CHANGELOG.md
Added changelog for fix https://github.com/VictoriaMetrics/grafana-datasource/pull/170
I have checked the possibility of moving logic from prettify query to the data source, which we discussed [here](https://github.com/VictoriaMetrics/grafana-datasource/pull/169#issuecomment-2182473349)
I think it is not a good idea to move logic by removing logic from the prettify component to another place because those changes only relate to the prettify functionality.
But I need another opinion about my thoughts
> follow up after 1b06a341fb22ad5652a258d77b577508bad70216

- README.md
See: https://github.com/VictoriaMetrics/victorialogs-datasource/issues/32
- update security context used for Grafana examples as it was changed in Grafana images
- make archive name unique to make it easier install VictoriaLogs and VictoriaMetrics datasources side by side
> docs/readme: update script examples

- CHANGELOG.md
- pkg/plugin/datasource.go
If the user wants to use some OAuth and set the Forward OAuth Identity flag, headers with bearer tokens are not sent to the proxy server. This PR fixed this problem
Related issue: https://github.com/VictoriaMetrics/victorialogs-datasource/issues/54
> fix issue with forwarding headers

- CHANGELOG.md
- src/querybuilder/state.ts
Set the default value of `Type` to `instant` when creating alerting rules. 
Related Issue: #205
> Set default Type to instant for alert rules

- CHANGELOG.md
- pkg/plugin/datasource.go
remove vmselect specific `/select/`-prefixed path part for /health endpoint requests. fixes https://github.com/VictoriaMetrics/victoriametrics-datasource/issues/208
> Fixed health endpoint

- .config/webpack/constants.ts
- .gitignore
- Makefile
- deployment/docker/Makefile
- package.json
- webpack.config.ts
Starting from Grafana v10.4.0 it tries to check the folder inside the defined plugin folder.
If we set
plugins = /Users/path/victorialogs-datasource Grafana tries to check source plugins in the src folder and shows the error that the backend file can be found
But if we declare the path like
plugins = /Users/path/plugins/victorialogs-datasource (we create a folder above our plugin) it works correctly.
Also started from Grafana v10.4.0 when we started it and defined the plugin folder it added its own plugin named
grafana-lokiexplore-app
Those changes are compatible with the previous version of Grafana
> update dev process

- CHANGELOG.md
- src/datasource.tsx
This PR resolves an issue where the `step` for returned results in annotation queries was calculated incorrectly, resulting in missed events. The issue was caused by the absence of the `maxDataPoints` parameter.
Related issue: #217
> Fix incorrect step calculation for annotation queries

- CHANGELOG.md
- src/datasource.tsx
Excessive escaping of characters when selecting metrics in Metrics Browser has been fixed.
The queries contained unnecessary escape characters. For example, when selecting the label `bios_date` with the value `09/13/2024`, the query was formed as `{bios_date\="09\/13\/2024"}`, which led to errors. Now the queries are correctly formed as `{bios_date="09/13/2024"}`.
Related issue: #214
> Fix escaping in metrics browser selection

- CHANGELOG.md
- src/datasource.tsx
Fix issue with variables not working in adhoc filters
Ref issue: #235
> fix adhoc filter variables

- CHANGELOG.md
- Makefile
- packages/lezer-metricsql/package.json
- webpack.config.ts
- yarn.lock
This PR fixed the issue with the frontend dependency. 
Before this fix lezer-metricsql was not included in the dependencies and Grafana shows an error.
> Fix issue with lezer-metricsql dependency and public folder

- pkg/main.go
This should reduce pollution in Grafana logs,
as suggested during plugin review for Grafana marketplace.
> backend: switch INFO logs to DEBUG level

- CHANGELOG.md
- pkg/plugin/step.go
- pkg/plugin/step_test.go
Fixed all possible combinations of the instant query. 
correctly calculate step for the instant query, use `5m` step for the alerting queries if interval wasn't explicitly set by user. This change reduces alerts flapping for Grafana managed alerts.
> Fix issue with default instant query for the alert panel

- CHANGELOG.md
- pkg/plugin/response.go
- pkg/plugin/response_test.go
Fixed problem when series was detected as not a wide series. It was happened because reponse had a typeInfo as [0, 0] instead of [0, 1].
See this [comment](https://github.com/VictoriaMetrics/victoriametrics-datasource/issues/286#issuecomment-2679231412) with the explanation.
Related issue: https://github.com/VictoriaMetrics/victoriametrics-datasource/issues/286
> Fix error when response detected as not a wide series

- CHANGELOG.md
- packages/lezer-metricsql/package.json
- packages/lezer-metricsql/src/metricsql.grammar
- src/language_utils.test.ts
- src/language_utils.ts
- src/querybuilder/components/PromQueryBuilder.tsx
- src/querybuilder/shared/LabelFilterItem.tsx
Automatically escape metric and label names in the query builder so that names with special characters (e.g. "3foo(b)ar") are handled correctly.
Related issue: #266
> Automatically escape metric and label names in the query builder

- CHANGELOG.md
- src/datasource.test.ts
- src/datasource.tsx
Fix timerange alignment to preserve the original range without unintended shifts
Related issue: #275
> fix timerange alignment

- CHANGELOG.md
- src/components/VmuiLink.tsx
This PR fixes an issue where the VMUI link was incorrectly set to `about:blank`. 
Related issue: #288
> fix incorrect vmui link address

- CHANGELOG.md
- package.json
- src/configuration/ConfigEditor.tsx
- yarn.lock
removed version constraint for secure proxy settings. for some reason a whole section is absent in grafana cloud
> removed version constraint for secure proxy settings

- package.json
- src/configuration/ConfigEditor.tsx
- src/querybuilder/parsing.test.ts
- src/querybuilder/parsing.ts
- src/querybuilder/shared/parsingUtils.ts
- yarn.lock
Fixes #317
Bringing sources closer to Prometheus Visual Query Builder code
Copied relevant tests
PromQL lezer grammar has also been updated recently, so maybe a good next step should be updating metricsql lezer grammar, this way it will be possible to bring visual query builder's sources even closer to grafana promql's
> Update visual query build from grafana upstream

- CHANGELOG.md
- src/language_provider.ts
- src/metricsql.ts
- Fixed incorrect label filter behavior for metric names with special characters. Related issue: #131
- Enabled support for dot characters in label names. Related issue: #205
> Fix special char handling in metrics and labels

- CHANGELOG.md
- src/querybuilder/components/LabelFilters.tsx
Related isuue: #319 
Problem was in grafana's component `Stack`, so just changed the grafana's `EditorList` to datasource implementation of `EditorList` component.
> fix issue in Grafana 10.1.5 where creating a variable using label_values is not possible

- CHANGELOG.md
- src/querybuilder/aggregations.ts
- src/querybuilder/metricsql-functions/aggregations/overTime.ts
- src/querybuilder/parsing.ts
Related issue: #316 
- added a rollup field to rollup_rate function
- fixed parsing of over_time functions
> add a rollup field to rollup_rate function

- CHANGELOG.md
- src/plugin.json
Updates `grafanaDependency` to `>=10.4.0` for compatibility with [@grafana/plugin-ui](https://github.com/grafana/plugin-ui).
This change drops support for Grafana versions earlier than `10.4.0`, so a major version bump of the plugin is recommended.
> bump Grafana minimum supported version to 10.4.0

- CHANGELOG.md
- pkg/plugin/datasource.go
- pkg/plugin/datasource_test.go
Fixed concurrent map writes when performing multiple requests 
Related issue: #363
> fix issue with concurrent map writes

- CHANGELOG.md
- pkg/plugin/step.go
- pkg/plugin/step_test.go
Related issue: #383 
Fixed unpredictable behavior when determining an interval for a range query  by updating interval comparison logic for `roundInterval` to use `<` instead of `<=` for consistency with grafana logic.
Fix is similar to [vl-datasource fix](https://github.com/VictoriaMetrics/victorialogs-datasource/pull/391)
> fix unpredictable behavior when determining an interval for a range query 

- CHANGELOG.md
- pkg/plugin/datasource_test.go
- pkg/plugin/response.go
- pkg/plugin/response_test.go
- pkg/plugin/utils.go
- pkg/plugin/utils_test.go
Related issue: #376 
Fixed issue with intervals less than 1 second not being handled correctly in time parsing by converting fractional part to string with milliseconds precision.
> fix issue with intervals less than 1 second not being handled correctly in time parsing

- .github/workflows/docs.yaml
- src/README.md
This change uses the public-facing src/readme.md as source for https://docs.victoriametrics.com/victoriametrics/victoriametrics-datasource/.
The `src/README.md` is readme displayed in Grafana's plugins catalogue. It is more user friendly and focused on using the plugin. While the current root's README.md has a lot of extra info about development and advanced installation methods that might be not relevant to majority of users.
> docs: use src/README.md as source for docs
